export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST"
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS"
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE"

export const GET_ONE_ITEM_REQUEST = "GET_ONE_ITEM_REQUEST"
export const GET_ONE_ITEM_SUCCESS = "GET_ONE_ITEM_SUCCESS"
export const GET_ONE_ITEM_FAILURE = "GET_ONE_ITEM_FAILURE"

export const POST_ITEM_REQUEST = "POST_ITEM_REQUEST"
export const POST_ITEM_SUCCESS = "POST_ITEM_SUCCESS"
export const POST_ITEM_FAILURE = "POST_ITEM_FAILURE"

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST"
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAILURE = "DELETE_ITEM_FAILURE"

export const PUT_ITEM_REQUEST = "PUT_ITEM_REQUEST"
export const PUT_ITEM_SUCCESS = "PUT_ITEM_SUCCESS"
export const PUT_ITEM_FAILURE = "PUT_ITEM_FAILURE"